// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

//go:build no_runtime_type_checking

package dataawsccs3bucket

// Building without runtime type checking enabled, so all the below just return nil

func (d *jsiiProxy_DataAwsccS3BucketReplicationConfigurationRulesSourceSelectionCriteriaReplicaModificationsOutputReference) validateGetAnyMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccS3BucketReplicationConfigurationRulesSourceSelectionCriteriaReplicaModificationsOutputReference) validateGetBooleanAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccS3BucketReplicationConfigurationRulesSourceSelectionCriteriaReplicaModificationsOutputReference) validateGetBooleanMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccS3BucketReplicationConfigurationRulesSourceSelectionCriteriaReplicaModificationsOutputReference) validateGetListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccS3BucketReplicationConfigurationRulesSourceSelectionCriteriaReplicaModificationsOutputReference) validateGetNumberAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccS3BucketReplicationConfigurationRulesSourceSelectionCriteriaReplicaModificationsOutputReference) validateGetNumberListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccS3BucketReplicationConfigurationRulesSourceSelectionCriteriaReplicaModificationsOutputReference) validateGetNumberMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccS3BucketReplicationConfigurationRulesSourceSelectionCriteriaReplicaModificationsOutputReference) validateGetStringAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccS3BucketReplicationConfigurationRulesSourceSelectionCriteriaReplicaModificationsOutputReference) validateGetStringMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccS3BucketReplicationConfigurationRulesSourceSelectionCriteriaReplicaModificationsOutputReference) validateInterpolationForAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccS3BucketReplicationConfigurationRulesSourceSelectionCriteriaReplicaModificationsOutputReference) validateResolveParameters(context cdktn.IResolveContext) error {
	return nil
}

func (j *jsiiProxy_DataAwsccS3BucketReplicationConfigurationRulesSourceSelectionCriteriaReplicaModificationsOutputReference) validateSetComplexObjectIndexParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_DataAwsccS3BucketReplicationConfigurationRulesSourceSelectionCriteriaReplicaModificationsOutputReference) validateSetComplexObjectIsFromSetParameters(val *bool) error {
	return nil
}

func (j *jsiiProxy_DataAwsccS3BucketReplicationConfigurationRulesSourceSelectionCriteriaReplicaModificationsOutputReference) validateSetInternalValueParameters(val *DataAwsccS3BucketReplicationConfigurationRulesSourceSelectionCriteriaReplicaModifications) error {
	return nil
}

func (j *jsiiProxy_DataAwsccS3BucketReplicationConfigurationRulesSourceSelectionCriteriaReplicaModificationsOutputReference) validateSetTerraformAttributeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_DataAwsccS3BucketReplicationConfigurationRulesSourceSelectionCriteriaReplicaModificationsOutputReference) validateSetTerraformResourceParameters(val cdktn.IInterpolatingParent) error {
	return nil
}

func validateNewDataAwsccS3BucketReplicationConfigurationRulesSourceSelectionCriteriaReplicaModificationsOutputReferenceParameters(terraformResource cdktn.IInterpolatingParent, terraformAttribute *string) error {
	return nil
}

