// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

//go:build no_runtime_type_checking

package dataawsccbedrockdataautomationproject

// Building without runtime type checking enabled, so all the below just return nil

func (d *jsiiProxy_DataAwsccBedrockDataAutomationProjectOverrideConfigurationVideoSensitiveDataConfigurationOutputReference) validateGetAnyMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccBedrockDataAutomationProjectOverrideConfigurationVideoSensitiveDataConfigurationOutputReference) validateGetBooleanAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccBedrockDataAutomationProjectOverrideConfigurationVideoSensitiveDataConfigurationOutputReference) validateGetBooleanMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccBedrockDataAutomationProjectOverrideConfigurationVideoSensitiveDataConfigurationOutputReference) validateGetListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccBedrockDataAutomationProjectOverrideConfigurationVideoSensitiveDataConfigurationOutputReference) validateGetNumberAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccBedrockDataAutomationProjectOverrideConfigurationVideoSensitiveDataConfigurationOutputReference) validateGetNumberListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccBedrockDataAutomationProjectOverrideConfigurationVideoSensitiveDataConfigurationOutputReference) validateGetNumberMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccBedrockDataAutomationProjectOverrideConfigurationVideoSensitiveDataConfigurationOutputReference) validateGetStringAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccBedrockDataAutomationProjectOverrideConfigurationVideoSensitiveDataConfigurationOutputReference) validateGetStringMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccBedrockDataAutomationProjectOverrideConfigurationVideoSensitiveDataConfigurationOutputReference) validateInterpolationForAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccBedrockDataAutomationProjectOverrideConfigurationVideoSensitiveDataConfigurationOutputReference) validateResolveParameters(context cdktn.IResolveContext) error {
	return nil
}

func (j *jsiiProxy_DataAwsccBedrockDataAutomationProjectOverrideConfigurationVideoSensitiveDataConfigurationOutputReference) validateSetComplexObjectIndexParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_DataAwsccBedrockDataAutomationProjectOverrideConfigurationVideoSensitiveDataConfigurationOutputReference) validateSetComplexObjectIsFromSetParameters(val *bool) error {
	return nil
}

func (j *jsiiProxy_DataAwsccBedrockDataAutomationProjectOverrideConfigurationVideoSensitiveDataConfigurationOutputReference) validateSetInternalValueParameters(val *DataAwsccBedrockDataAutomationProjectOverrideConfigurationVideoSensitiveDataConfiguration) error {
	return nil
}

func (j *jsiiProxy_DataAwsccBedrockDataAutomationProjectOverrideConfigurationVideoSensitiveDataConfigurationOutputReference) validateSetTerraformAttributeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_DataAwsccBedrockDataAutomationProjectOverrideConfigurationVideoSensitiveDataConfigurationOutputReference) validateSetTerraformResourceParameters(val cdktn.IInterpolatingParent) error {
	return nil
}

func validateNewDataAwsccBedrockDataAutomationProjectOverrideConfigurationVideoSensitiveDataConfigurationOutputReferenceParameters(terraformResource cdktn.IInterpolatingParent, terraformAttribute *string) error {
	return nil
}

