// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

//go:build no_runtime_type_checking

package dataawsccbedrockdatasource

// Building without runtime type checking enabled, so all the below just return nil

func (d *jsiiProxy_DataAwsccBedrockDataSourceVectorIngestionConfigurationCustomTransformationConfigurationOutputReference) validateGetAnyMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccBedrockDataSourceVectorIngestionConfigurationCustomTransformationConfigurationOutputReference) validateGetBooleanAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccBedrockDataSourceVectorIngestionConfigurationCustomTransformationConfigurationOutputReference) validateGetBooleanMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccBedrockDataSourceVectorIngestionConfigurationCustomTransformationConfigurationOutputReference) validateGetListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccBedrockDataSourceVectorIngestionConfigurationCustomTransformationConfigurationOutputReference) validateGetNumberAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccBedrockDataSourceVectorIngestionConfigurationCustomTransformationConfigurationOutputReference) validateGetNumberListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccBedrockDataSourceVectorIngestionConfigurationCustomTransformationConfigurationOutputReference) validateGetNumberMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccBedrockDataSourceVectorIngestionConfigurationCustomTransformationConfigurationOutputReference) validateGetStringAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccBedrockDataSourceVectorIngestionConfigurationCustomTransformationConfigurationOutputReference) validateGetStringMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccBedrockDataSourceVectorIngestionConfigurationCustomTransformationConfigurationOutputReference) validateInterpolationForAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccBedrockDataSourceVectorIngestionConfigurationCustomTransformationConfigurationOutputReference) validateResolveParameters(context cdktn.IResolveContext) error {
	return nil
}

func (j *jsiiProxy_DataAwsccBedrockDataSourceVectorIngestionConfigurationCustomTransformationConfigurationOutputReference) validateSetComplexObjectIndexParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_DataAwsccBedrockDataSourceVectorIngestionConfigurationCustomTransformationConfigurationOutputReference) validateSetComplexObjectIsFromSetParameters(val *bool) error {
	return nil
}

func (j *jsiiProxy_DataAwsccBedrockDataSourceVectorIngestionConfigurationCustomTransformationConfigurationOutputReference) validateSetInternalValueParameters(val *DataAwsccBedrockDataSourceVectorIngestionConfigurationCustomTransformationConfiguration) error {
	return nil
}

func (j *jsiiProxy_DataAwsccBedrockDataSourceVectorIngestionConfigurationCustomTransformationConfigurationOutputReference) validateSetTerraformAttributeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_DataAwsccBedrockDataSourceVectorIngestionConfigurationCustomTransformationConfigurationOutputReference) validateSetTerraformResourceParameters(val cdktn.IInterpolatingParent) error {
	return nil
}

func validateNewDataAwsccBedrockDataSourceVectorIngestionConfigurationCustomTransformationConfigurationOutputReferenceParameters(terraformResource cdktn.IInterpolatingParent, terraformAttribute *string) error {
	return nil
}

