// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

//go:build no_runtime_type_checking

package dataawsccglueconnectiontype

// Building without runtime type checking enabled, so all the below just return nil

func (d *jsiiProxy_DataAwsccGlueConnectionTypeConnectorAuthenticationConfigurationBasicAuthenticationPropertiesOutputReference) validateGetAnyMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccGlueConnectionTypeConnectorAuthenticationConfigurationBasicAuthenticationPropertiesOutputReference) validateGetBooleanAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccGlueConnectionTypeConnectorAuthenticationConfigurationBasicAuthenticationPropertiesOutputReference) validateGetBooleanMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccGlueConnectionTypeConnectorAuthenticationConfigurationBasicAuthenticationPropertiesOutputReference) validateGetListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccGlueConnectionTypeConnectorAuthenticationConfigurationBasicAuthenticationPropertiesOutputReference) validateGetNumberAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccGlueConnectionTypeConnectorAuthenticationConfigurationBasicAuthenticationPropertiesOutputReference) validateGetNumberListAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccGlueConnectionTypeConnectorAuthenticationConfigurationBasicAuthenticationPropertiesOutputReference) validateGetNumberMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccGlueConnectionTypeConnectorAuthenticationConfigurationBasicAuthenticationPropertiesOutputReference) validateGetStringAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccGlueConnectionTypeConnectorAuthenticationConfigurationBasicAuthenticationPropertiesOutputReference) validateGetStringMapAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccGlueConnectionTypeConnectorAuthenticationConfigurationBasicAuthenticationPropertiesOutputReference) validateInterpolationForAttributeParameters(terraformAttribute *string) error {
	return nil
}

func (d *jsiiProxy_DataAwsccGlueConnectionTypeConnectorAuthenticationConfigurationBasicAuthenticationPropertiesOutputReference) validateResolveParameters(context cdktn.IResolveContext) error {
	return nil
}

func (j *jsiiProxy_DataAwsccGlueConnectionTypeConnectorAuthenticationConfigurationBasicAuthenticationPropertiesOutputReference) validateSetComplexObjectIndexParameters(val interface{}) error {
	return nil
}

func (j *jsiiProxy_DataAwsccGlueConnectionTypeConnectorAuthenticationConfigurationBasicAuthenticationPropertiesOutputReference) validateSetComplexObjectIsFromSetParameters(val *bool) error {
	return nil
}

func (j *jsiiProxy_DataAwsccGlueConnectionTypeConnectorAuthenticationConfigurationBasicAuthenticationPropertiesOutputReference) validateSetInternalValueParameters(val *DataAwsccGlueConnectionTypeConnectorAuthenticationConfigurationBasicAuthenticationProperties) error {
	return nil
}

func (j *jsiiProxy_DataAwsccGlueConnectionTypeConnectorAuthenticationConfigurationBasicAuthenticationPropertiesOutputReference) validateSetTerraformAttributeParameters(val *string) error {
	return nil
}

func (j *jsiiProxy_DataAwsccGlueConnectionTypeConnectorAuthenticationConfigurationBasicAuthenticationPropertiesOutputReference) validateSetTerraformResourceParameters(val cdktn.IInterpolatingParent) error {
	return nil
}

func validateNewDataAwsccGlueConnectionTypeConnectorAuthenticationConfigurationBasicAuthenticationPropertiesOutputReferenceParameters(terraformResource cdktn.IInterpolatingParent, terraformAttribute *string) error {
	return nil
}

